/**
 * Apply all Drizzle migration SQL files to the dev PGlite DB (or prod
 * Postgres via DATABASE_URL=postgres://…).
 *
 * Why not just use `drizzle-kit push`? Because drizzle-kit's pglite
 * driver-mode has path-resolution quirks. This script reads the SAME
 * `db` client our app uses, so dev ↔ prod parity is guaranteed.
 *
 * The migration SQL generated by drizzle-kit contains
 * `--> statement-breakpoint` markers between statements. We split on
 * those markers and apply each statement individually — that way
 * (a) PGlite's multi-statement quirks don't bite us, and (b) we get
 * a precise error pointing at the failing statement.
 *
 * Usage:
 *   bun run scripts/db-migrate.ts           # apply all migrations
 *   bun run scripts/db-migrate.ts --list    # list pending files only
 */

import "dotenv/config";
import { readdir, readFile, mkdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";
import { db } from "../src/db/client";
import { sql } from "drizzle-orm";

async function main() {
  const dir = join(process.cwd(), "drizzle");
  if (!existsSync(dir)) {
    console.error(`No drizzle/ directory at ${dir}. Run \`bun run db:generate\` first.`);
    process.exit(1);
  }

  // PGlite wants the parent directory to exist before it can create
  // the data file. For dev that's `db/`.
  const dataDir = join(process.cwd(), "db");
  if (!existsSync(dataDir)) {
    await mkdir(dataDir, { recursive: true });
  }

  const files = (await readdir(dir))
    .filter((f) => f.endsWith(".sql"))
    .sort();
  console.log(`Found ${files.length} migration file(s):`);
  for (const f of files) console.log(`  - ${f}`);

  if (process.argv.includes("--list")) return;

  for (const f of files) {
    const sqlText = await readFile(join(dir, f), "utf8");
    console.log(`\nApplying ${f}...`);

    // Split on `--> statement-breakpoint` markers. Drizzle-kit emits
    // them inline after semicolons (`;--> statement-breakpoint`), so
    // we just split on the marker itself, then trim trailing ';' off
    // each piece. PGlite wraps queries in prepared statements which
    // reject multi-statement strings, so per-statement execution is
    // mandatory.
    const statements = sqlText
      .split(/-->\s*statement-breakpoint\s*\n?/)
      .map((s) => s.trim().replace(/;$/, ""))
      .filter((s) => s.length > 0 && !s.startsWith("--"));

    console.log(`  ${statements.length} statement(s) to apply`);

    for (let i = 0; i < statements.length; i++) {
      const stmt = statements[i];
      const preview = stmt.length > 80 ? stmt.slice(0, 80) + "..." : stmt;
      try {
        await db.execute(sql.raw(stmt));
      } catch (err: any) {
        // Drizzle wraps errors in DrizzleQueryError; the real PG error
        // is in err.cause. Surface both for debugging.
        const cause = err?.cause ?? err;
        console.error(`\n  ✗ Statement ${i + 1} failed:`);
        console.error(`    SQL: ${preview}`);
        if (cause?.message) console.error(`    Message: ${cause.message}`);
        if (cause?.code) console.error(`    Code: ${cause.code}`);
        if (cause?.detail) console.error(`    Detail: ${cause.detail}`);
        if (cause?.hint) console.error(`    Hint: ${cause.hint}`);
        if (cause?.where) console.error(`    Where: ${cause.where}`);
        process.exit(1);
      }
    }
    console.log(`  OK`);
  }
  console.log("\n✅ All migrations applied.");
}

main().catch((err) => {
  console.error("Migration failed:", err?.message ?? err);
  process.exit(1);
});
